### ISSUE TITLE
Build Error: Unable to Find Required Dependencies in Android Project

### ISSUE THREAD

**Issue by ankitkumar1302** [Faceplugin-ltd/FaceRecognition-LivenessDetection-Android#3]
# Build Failure: Unable to Resolve Dependencies in `:app:debugRuntimeClasspath`

## Summary

I am experiencing build failures in my Android project due to unresolved dependencies in the `:app:debugRuntimeClasspath` configuration. The errors occur during the tasks `:app:desugarDebugFileDependencies` and `:app:mergeDebugNativeLibs`.

### Task 1: `:app:desugarDebugFileDependencies`

**Error Message:**

Execution failed for task ':app
'.

Could not resolve all files for configuration ':app
'.
Could not find io.fotoapparat:fotoapparat:2.7.0.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
- https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
- https://jcenter.bintray.com/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
Required by:
project
Could not find com.royrodriguez:transitionbutton:0.2.0.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/com/royrodriguez/transitionbutton/0.2.0/transitionbutton-0.2.0.pom
- https://repo.maven.apache.org/maven2/com/royrodriguez/transitionbutton/0.2.0/transitionbutton-0.2.0.pom
- https://jcenter.bintray.com/com/royrodriguez/transitionbutton/0.2.0/transitionbutton-0.2.0.pom
Required by:
project
Could not find com.github.ybq:Android-SpinKit:1.4.0.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/com/github/ybq/Android-SpinKit/1.4.0/Android-SpinKit-1.4.0.pom
- https://repo.maven.apache.org/maven2/com/github/ybq/Android-SpinKit/1.4.0/Android-SpinKit-1.4.0.pom
- https://jcenter.bintray.com/com/github/ybq/Android-SpinKit/1.4.0/Android-SpinKit-1.4.0.pom
Required by:
project

javascript
Copy code

### Task 2: `:app:mergeDebugNativeLibs`

**Error Message:**

Execution failed for task ':app
'.

Could not resolve all files for configuration ':app
'.
Could not find io.fotoapparat:fotoapparat:2.7.0.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
- https://repo.maven.apache.org/maven2/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
- https://jcenter.bintray.com/io/fotoapparat/fotoapparat/2.7.0/fotoapparat-2.7.0.pom
Required by:
project
Could not find com.royrodriguez:transitionbutton:0.2.0.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/com/royrodriguez/transitionbutton/0.2.0/transitionbutton-0.2.0.pom
- https://repo.maven.apache.org/maven2/com/royrodriguez/transitionbutton/0.2.0/transitionbutton-0.2.0.pom
- https://jcenter.bintray.com/com/royrodriguez/transitionbutton/0.2.0/transitionbutton-0.2.0.pom
Required by:
project
Could not find com.github.ybq:Android-SpinKit:1.4.0.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/com/github/ybq/Android-SpinKit/1.4.0/Android-SpinKit-1.4.0.pom
- https://repo.maven.apache.org/maven2/com/github/ybq/Android-SpinKit/1.4.0/Android-SpinKit-1.4.0.pom
- https://jcenter.bintray.com/com/github/ybq/Android-SpinKit/1.4.0/Android-SpinKit-1.4.0.pom
Required by:
project

markdown
Copy code

## Steps to Reproduce

1. Clone the repository.
2. Attempt to build the project using Gradle.
3. The build fails during the `:app:desugarDebugFileDependencies` and `:app:mergeDebugNativeLibs` tasks.

## Expected Behavior

The build should succeed without any issues, and all dependencies should be resolved correctly.

## Actual Behavior

The build fails due to unresolved dependencies, specifically for the following libraries:
- `io.fotoapparat:fotoapparat:2.7.0`
- `com.royrodriguez:transitionbutton:0.2.0`
- `com.github.ybq:Android-SpinKit:1.4.0`

## Additional Information

- I have verified that the mentioned dependencies are correctly specified in the `build.gradle` file.
- I have tried cleaning the project and rebuilding it, but the issue persists.
- Deprecated Gradle features are being used, which might cause issues with Gradle 8.0 compatibility.
  
## Environment

- **Gradle Version:** 7.5
- **Android Studio Version:** [Insert Version Here]
- **Operating System:** [Insert OS Version Here]

## Potential Solutions

1. Verify the availability of the mentioned dependencies in the specified repositories.
2. Consider alternative repositories or dependencies if the current ones are no longer available.

## Logs

For more details, here are the logs:

- Run with `--stacktrace` for more detailed logs.
- Run with `--info` or `--debug` for additional output.
- Use `--scan` for full build insights.

 
 
 How to solve this error.

**Comment by andyfaceplugin** [comment]
Hi Can we do a live session to resolve your issue?

**Comment by andyfaceplugin** [comment]
It has been solved now.
Sorry for being late

**Comment by ankitkumar1302** [comment]
Whats the price of you SDK ?
I need for commercial use

**Comment by andyfaceplugin** [comment]
Please reach out to me on Whatspp.
+1 (442) 229-5661
